Add button
natsukikokubu/ts_medical_app pull request #2
Opened 2023-08-31 15:41 UTC by natsukikokubu

## 変更点

- Tailwind追加
- favicon追加
- ボタンコンポーネント追加

## 確認してほしいこと

- [ ] Tailwindが反映されている
- [ ] faviconがある
- [ ] ボタンコンポーネントが適切に作られている
- [ ] Home.tsxのスタートボタンを押すとListページに遷移する

2023-09-01 05:52 UTC, tachibanayu24 requested changes
今そこまで考えるのは難しいかもしれませんが、このPRでは

* react-routerを導入してページルーティングを実装
* tailwindを適用
* 空のページを作成
* Buttonコンポーネントを作成

と4つの関心を扱っています。
以下のようにPRを分けることができると思います。

* react-routerを導入してページルーティングを実装
  * 空のページも同時に作成
* tailwindを適用
  * Buttonコンポーネントも同時に作成


基本的に、関心が散っていない単位でPRを出すと良いです

2023-09-01 05:52 UTC, tachibanayu24 commented on README.md
> +$ npm run format :write
```suggestion
$ npm run format:write
```

では

2023-09-01 05:52 UTC, tachibanayu24 commented on src/App.tsx
> +      <Route path="/chatgpt" element={<Chatgpt />} />
chatgptというのは利用する技術に対する関心だけなので、chatgptでなにをするかというのを考えてURLを決めるといいかと思います

2023-09-01 05:52 UTC, tachibanayu24 commented on src/components/Button.tsx
> +  variant: 'start' | 'next'
start, nextというのは具体的なユースケースに則ったものになるので、variantの命名としては不適切かと
つまり、startと同じstyleのボタンを使いたいけど、startとは異なるようなユースケースで利用するときにも、variant=startと指定しなければならない可能性があります。

variant: primaryとかsuccess
または、color: blue
など、具体的なユースケースに言及しないほうが抽象コンポーネントとしては適当です

2023-09-01 05:52 UTC, tachibanayu24 commented on src/components/Button.tsx
> +  console.log(variant)
logは消してからマージすること

2023-09-01 05:52 UTC, tachibanayu24 commented on src/pages/Explanation.tsx
> +}
先にページの入れ物だけ作っておくのはとてもいいと思います

2023-09-01 05:52 UTC, tachibanayu24 commented on src/pages/Home.tsx
> +      <Link to="/List">go to List page</Link>
```suggestion
      <Link to="/list">go to List page</Link>
```

2023-09-03 04:38 UTC, natsukikokubu commented
修正をコミットしました。
作業を進めていた分、新しく治療一覧もコミットされてしまいました。
一旦修正部分だけリレビューをお願いします！

2023-09-04 17:22 UTC, tachibanayu24 reviewed
@natsukikokubu 
レビューしたので、ご自身の判断でマージしてもいいです
修正してre-review依頼をしてもいいです

2023-09-04 17:22 UTC, tachibanayu24 commented on src/pages/List.tsx
> +      </h2>
`dark:` のprefixつきのclassNameはダークモードのときのstyleを付与するものだったはずで、
デフォルトではOSの設定に依存するようになっていた気が
![Screenshot 2023-09-05 at 2 19 44](https://github.com/natsukikokubu/ts_medical_app/assets/23476543/fef76e61-3b0c-4f2f-bc18-23e0b642fc63)

ダークモードの対応をする予定がないのであればこういうのは消していいかと

2023-09-04 17:22 UTC, tachibanayu24 commented on src/pages/List.tsx
> +      </a>
似たようなUIなのでコンポーネントとして切り出していいような気がしますね
Cardとかそんな命名がいいかなぁ

2023-09-04 17:22 UTC, tachibanayu24 commented on src/pages/List.tsx
> +      </a>
まあ別PRでやってもいいですが

2023-09-04 17:22 UTC, tachibanayu24 commented on src/components/Button.tsx
> +  variant: 'primary'
本当は最初の定義でvariantを想定できるものを全部定義したほうがいいんですが、まあ使うときに定義を追加でもいいです

2023-09-05 01:43 UTC, merged